### ISSUE TITLE
Can I merge two instructions for Raydium and Mercurial?

### ISSUE THREAD

**Issue by IT-Prince** [mercurial-finance/stable-swap-n-pool-js#2]
I am trying to swap RAY to weUSDC
I need to swap from RAY to USDC using Raydium
and then USDC to weUSDC via Mercurial

I was trying to merge these two transactions in one
but exceed the limit of compute units 
Is there anyway to fix it?

**Comment by siong1987** [comment]
@IT-Prince there is nothing you can really do if you exceed the compute units. it is a current limitation on Solana now.
